import SpotifyWebApi from "spotify-web-api-js";

const spotifyApi = new SpotifyWebApi();

const moodGenreMapping = {
  happy: ["pop", "electronic"],
  energetic: ["rock", "hip-hop"],
  relaxed: ["classical", "jazz"],
  romantic: ["pop", "indie"],
  melancholic: ["indie", "rock"],
  workout: ["electronic", "hip-hop"],
};

const shuffleArray = (array) => {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
  return array;
};

export const generatePlaylist = async (mood, genres) => {
  const recommendedGenres =
    genres.length > 0 ? genres : moodGenreMapping[mood] || [];

  const tracks = [];
  for (const genre of recommendedGenres) {
    try {
      const response = await spotifyApi.searchTracks(`genre:${genre}`, {
        limit: 50, // Increase the limit to get more tracks
      });
      if (response.tracks && response.tracks.items) {
        tracks.push(...response.tracks.items);
      } else {
        console.error(`No tracks found for genre ${genre}`);
      }
    } catch (error) {
      console.error(`Error fetching tracks for genre ${genre}:`, error);
    }
  }

  if (tracks.length === 0) {
    console.error("No tracks found for the selected mood and genres.");
    return {
      id: "1",
      title: "Mood Mix",
      tracks: [],
    };
  }

  // Shuffle the tracks to ensure randomness
  const shuffledTracks = shuffleArray(tracks);

  const selectedTracks = shuffledTracks.slice(0, 30).map((track) => ({
    id: track.id,
    name: track.name,
    artist: track.artists[0].name,
    genre:
      track.genres && track.genres.length > 0 ? track.genres[0] : "unknown",
    albumCover: track.album.images[0]?.url || "",
  }));

  const playlistTitle = `Mood Mix: ${mood} ${genres.join(", ")}`;

  const playlist = {
    id: "1",
    title: playlistTitle,
    tracks: selectedTracks,
  };

  return playlist;
};

export const savePlaylist = async (playlist) => {
  try {
    const user = await spotifyApi.getMe();
    const newPlaylist = await spotifyApi.createPlaylist(user.id, {
      name: playlist.title,
      description: "Generated by Mood Playlist Generator",
      public: false,
    });

    const trackUris = playlist.tracks.map(
      (track) => `spotify:track:${track.id}`
    );
    await spotifyApi.addTracksToPlaylist(newPlaylist.id, trackUris);

    // Save playlist to database
    await savePlaylistToDatabase({
      userId: user.id,
      playlistId: newPlaylist.id,
      title: playlist.title,
      tracks: playlist.tracks,
    });

    return { success: true, playlistId: newPlaylist.id };
  } catch (error) {
    console.error("Error saving playlist:", error);
    return { success: false, error: error.message };
  }
};

const savePlaylistToDatabase = async (playlist) => {
  try {
    console.log(
      "Saving playlist to database with URL: http://localhost:3000/api/playlists"
    );
    const response = await fetch("http://localhost:3000/api/playlists", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(playlist),
    });

    if (!response.ok) {
      throw new Error("Failed to save playlist to database");
    }

    return await response.json();
  } catch (error) {
    console.error("Error saving playlist to database:", error);
    throw error;
  }
};

export const getRecommendedTracks = async () => {
  try {
    const userPlaylists = await spotifyApi.getUserPlaylists();
    const trackIds = [];

    for (const playlist of userPlaylists.items) {
      const tracks = await spotifyApi.getPlaylistTracks(playlist.id);
      tracks.items.forEach((item) => {
        trackIds.push(item.track.id);
      });
    }

    console.log("Track IDs for recommendations:", trackIds);

    const seedTracks = trackIds.slice(0, 5); // Use up to 5 seed tracks
    if (seedTracks.length === 0) {
      console.error("No seed tracks available for recommendations.");
      return [];
    }

    const recommendationsUrl = `https://api.spotify.com/v1/recommendations?seed_tracks=${seedTracks.join(
      ","
    )}&limit=20`;
    console.log("Recommendations URL:", recommendationsUrl);

    const recommendations = await spotifyApi.getRecommendations({
      seed_tracks: seedTracks,
      limit: 20, // Number of recommended tracks
    });

    console.log("Recommendations:", recommendations);

    if (!recommendations.tracks || recommendations.tracks.length === 0) {
      console.error("No recommendations found.");
      return [];
    }

    return recommendations.tracks.map((track) => ({
      id: track.id,
      name: track.name,
      artist: track.artists[0].name,
      albumCover: track.album.images[0]?.url || "",
    }));
  } catch (error) {
    console.error("Error getting recommended tracks:", error);
    throw error;
  }
};
