import SpotifyWebApi from "spotify-web-api-js";

const spotifyApi = new SpotifyWebApi();

const moodGenreMapping = {
  happy: ["pop", "electronic"],
  energetic: ["rock", "hip-hop"],
  relaxed: ["classical", "jazz"],
  romantic: ["pop", "indie"],
  melancholic: ["indie", "rock"],
  workout: ["electronic", "hip-hop"],
};

export const generatePlaylist = async (mood, genres) => {
  // Filter genres based on mood
  const recommendedGenres =
    genres.length > 0 ? genres : moodGenreMapping[mood] || [];

  // Fetch real tracks from Spotify API
  const tracks = [];
  for (const genre of recommendedGenres) {
    try {
      const response = await spotifyApi.searchTracks(`genre:${genre}`, {
        limit: 5,
      });
      tracks.push(...response.tracks.items);
    } catch (error) {
      console.error(`Error fetching tracks for genre ${genre}:`, error);
    }
  }

  // Ensure we have 10 tracks
  const selectedTracks = tracks.slice(0, 10).map((track) => ({
    id: track.id,
    name: track.name,
    artist: track.artists[0].name,
    genre:
      track.genres && track.genres.length > 0 ? track.genres[0] : "unknown",
  }));

  // Dummy playlist generation
  const playlist = {
    id: "1",
    title: "Mood Mix",
    tracks: selectedTracks,
  };

  return playlist;
};

export const savePlaylist = async (playlist) => {
  try {
    // Create a new playlist
    const user = await spotifyApi.getMe();
    const newPlaylist = await spotifyApi.createPlaylist(user.id, {
      name: playlist.title,
      description: "Generated by Mood Playlist Generator",
      public: false,
    });

    // Add tracks to the new playlist
    const trackUris = playlist.tracks.map(
      (track) => `spotify:track:${track.id}`
    );
    await spotifyApi.addTracksToPlaylist(newPlaylist.id, trackUris);

    console.log("Playlist saved:", newPlaylist);
    return { success: true, playlistId: newPlaylist.id };
  } catch (error) {
    console.error("Error saving playlist:", error);
    if (error.response) {
      console.error("Response data:", error.response.data);
      console.error("Response status:", error.response.status);
      console.error("Response headers:", error.response.headers);
    } else {
      console.error("Error message:", error.message);
    }
    return { success: false, error: error.message };
  }
};
